PACKAGE_IMPORT_NAMES = {
    'betterproto': ['betterproto'],
    'ctranslate2': ['ctranslate2'],
    'deepl': ['deepl'],
    'diffusers': ['diffusers'],
    'einops': ['einops'],
    'gguf': ['gguf'],
    'httpx': ['httpx'],
    'jaconv': ['jaconv'],
    'msl-loadlib': ['msl'],
    'openai': ['openai'],
    'onnxruntime': ['onnxruntime'],
    'onnxruntime-gpu': ['onnxruntime'],
    'pyspellchecker': ['spellchecker'],
    'pyobjc-framework-vision': ['Vision', 'objc'],
    'pyyaml': ['yaml'],
    'safetensors': ['safetensors'],
    'sentencepiece': ['sentencepiece'],
    'torch': ['torch'],
    'torchvision': ['torchvision'],
    'transformers': ['transformers'],
    'translators': ['translators'],
    'ultralytics': ['ultralytics'],
    'winsdk': ['winsdk'],
}
