# This file is auto-generated by scripts/update_translation.py.
# Do not edit by hand; rerun the script after changing module parameter metadata.

from qtpy.QtCore import QCoreApplication

MODULE_PARAM_CATALOG = {
    ('inpainter', 'LLMInpaint', '', 'description'): {
        "source": 'Inpaint using the selected image-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint using the selected image-capable LLM profile.'),
    },
    ('inpainter', 'LLMInpaint', 'delay', 'description'): {
        "source": 'Delay between LLM image cleanup requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM image cleanup requests in seconds.'),
    },
    ('inpainter', 'LLMInpaint', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('inpainter', 'LLMInpaint', 'inpaint by block', 'description'): {
        "source": 'Send each text block crop separately instead of sending the whole image.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Send each text block crop separately instead of sending the whole image.'),
    },
    ('inpainter', 'LLMInpaint', 'inpaint by block', 'display_name'): {
        "source": 'Inpaint By Block', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint By Block'),
    },
    ('inpainter', 'LLMInpaint', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM image cleanup.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM image cleanup.'),
    },
    ('inpainter', 'LLMInpaint', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('inpainter', 'LLMInpaint', 'max resolution', 'description'): {
        "source": 'Scale images down before sending them to the LLM. Set to 0 to keep the original size.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Scale images down before sending them to the LLM. Set to 0 to keep the original size.'),
    },
    ('inpainter', 'LLMInpaint', 'max resolution', 'display_name'): {
        "source": 'Max Resolution', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Resolution'),
    },
    ('inpainter', 'LLMInpaint', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('inpainter', 'LLMInpaint', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('inpainter', 'LLMInpaint', 'request timeout', 'description'): {
        "source": 'HTTP timeout for image cleanup requests in seconds. Set to 0 to disable.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'HTTP timeout for image cleanup requests in seconds. Set to 0 to disable.'),
    },
    ('inpainter', 'LLMInpaint', 'request timeout', 'display_name'): {
        "source": 'Request Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Request Timeout'),
    },
    ('inpainter', 'LLMInpaint', 'retry attempts', 'description'): {
        "source": 'Retries for API failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API failures.'),
    },
    ('inpainter', 'LLMInpaint', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('inpainter', 'LLMInpaint', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('inpainter', 'LLMInpaint', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('inpainter', 'aot', '', 'description'): {
        "source": 'manga-image-translator inpainter', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'manga-image-translator inpainter'),
    },
    ('inpainter', 'aot', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'aot', 'inpaint_size', 'display_name'): {
        "source": 'Inpaint Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint Size'),
    },
    ('inpainter', 'flux2-klein', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'flux2-klein', 'max_resolution', 'display_name'): {
        "source": 'Max Resolution', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Resolution'),
    },
    ('inpainter', 'flux2-klein', 'model', 'display_name'): {
        "source": 'model', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'model'),
    },
    ('inpainter', 'flux2-klein', 'step', 'display_name'): {
        "source": 'step', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'step'),
    },
    ('inpainter', 'lama_large_512px', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'lama_large_512px', 'inpaint_size', 'display_name'): {
        "source": 'Inpaint Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint Size'),
    },
    ('inpainter', 'lama_large_512px', 'precision', 'display_name'): {
        "source": 'precision', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'precision'),
    },
    ('inpainter', 'lama_mpe', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'lama_mpe', 'inpaint_size', 'display_name'): {
        "source": 'Inpaint Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint Size'),
    },
    ('ocr', 'LLMOCR', '', 'description'): {
        "source": 'OCR using the selected vision-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using the selected vision-capable LLM profile.'),
    },
    ('ocr', 'LLMOCR', 'delay', 'description'): {
        "source": 'Delay between LLM OCR requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM OCR requests in seconds.'),
    },
    ('ocr', 'LLMOCR', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('ocr', 'LLMOCR', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM OCR.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM OCR.'),
    },
    ('ocr', 'LLMOCR', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('ocr', 'LLMOCR', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('ocr', 'LLMOCR', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('ocr', 'LLMOCR', 'retry attempts', 'description'): {
        "source": 'Retries for API failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API failures.'),
    },
    ('ocr', 'LLMOCR', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('ocr', 'LLMOCR', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('ocr', 'LLMOCR', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('ocr', 'PaddleOCRVLManga', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'PaddleOCRVLManga', 'max_new_tokens', 'description'): {
        "source": 'Max generation tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max generation tokens'),
    },
    ('ocr', 'PaddleOCRVLManga', 'max_new_tokens', 'display_name'): {
        "source": 'Max New Tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max New Tokens'),
    },
    ('ocr', 'google_lens_exp', '', 'description'): {
        "source": 'OCR using Google Lens Protobuf API (requests backend)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using Google Lens Protobuf API (requests backend)'),
    },
    ('ocr', 'google_lens_exp', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('ocr', 'google_lens_exp', 'newline_handling', 'description'): {
        "source": 'Handle newline characters in the final OCR string.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Handle newline characters in the final OCR string.'),
    },
    ('ocr', 'google_lens_exp', 'newline_handling', 'display_name'): {
        "source": 'Newline Handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Newline Handling'),
    },
    ('ocr', 'google_lens_exp', 'no_uppercase', 'description'): {
        "source": 'Convert text to lowercase except first letter of sentences.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Convert text to lowercase except first letter of sentences.'),
    },
    ('ocr', 'google_lens_exp', 'no_uppercase', 'display_name'): {
        "source": 'No Uppercase', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'No Uppercase'),
    },
    ('ocr', 'google_lens_exp', 'proxy', 'description'): {
        "source": 'Proxy (requests format: e.g., http://user:pass@host:port or {"http": ..., "https": ...})', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy (requests format: e.g., http://user:pass@host:port or {"http": ..., "https": ...})'),
    },
    ('ocr', 'google_lens_exp', 'proxy', 'display_name'): {
        "source": 'proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'proxy'),
    },
    ('ocr', 'google_lens_exp', 'target_language', 'description'): {
        "source": "Target language code (e.g., 'ja', 'en', 'ru').", "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', "Target language code (e.g., 'ja', 'en', 'ru')."),
    },
    ('ocr', 'google_lens_exp', 'target_language', 'display_name'): {
        "source": 'Target Language', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Target Language'),
    },
    ('ocr', 'google_screen_ai_ocr', '', 'description'): {
        "source": 'Google ScreenAI OCR engine. Automatically downloads files on module load.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Google ScreenAI OCR engine. Automatically downloads files on module load.'),
    },
    ('ocr', 'google_screen_ai_ocr', 'light_mode', 'description'): {
        "source": 'Use the faster, lighter ScreenAI OCR model', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Use the faster, lighter ScreenAI OCR model'),
    },
    ('ocr', 'google_screen_ai_ocr', 'light_mode', 'display_name'): {
        "source": 'Light Mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Light Mode'),
    },
    ('ocr', 'google_screen_ai_ocr', 'newline_handling', 'description'): {
        "source": 'Choose how to handle newline characters in OCR results', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Choose how to handle newline characters in OCR results'),
    },
    ('ocr', 'google_screen_ai_ocr', 'newline_handling', 'display_name'): {
        "source": 'Newline Handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Newline Handling'),
    },
    ('ocr', 'google_vision', '', 'description'): {
        "source": 'OCR using Google Vision API', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using Google Vision API'),
    },
    ('ocr', 'google_vision', 'api_key', 'display_name'): {
        "source": 'API Key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API Key'),
    },
    ('ocr', 'google_vision', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('ocr', 'google_vision', 'language_hints', 'description'): {
        "source": 'Language codes separated by commas (BCP-47)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Language codes separated by commas (BCP-47)'),
    },
    ('ocr', 'google_vision', 'language_hints', 'display_name'): {
        "source": 'Language Hints', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Language Hints'),
    },
    ('ocr', 'google_vision', 'newline_handling', 'description'): {
        "source": 'Choose how to handle newline characters in OCR results', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Choose how to handle newline characters in OCR results'),
    },
    ('ocr', 'google_vision', 'newline_handling', 'display_name'): {
        "source": 'Newline Handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Newline Handling'),
    },
    ('ocr', 'google_vision', 'no_uppercase', 'description'): {
        "source": 'Convert text to lowercase except the first letter of each sentence', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Convert text to lowercase except the first letter of each sentence'),
    },
    ('ocr', 'google_vision', 'no_uppercase', 'display_name'): {
        "source": 'No Uppercase', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'No Uppercase'),
    },
    ('ocr', 'google_vision', 'proxy', 'description'): {
        "source": 'Proxy address (e.g., http(s)://user:password@host:port or socks4/5://user:password@host:port)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address (e.g., http(s)://user:password@host:port or socks4/5://user:password@host:port)'),
    },
    ('ocr', 'google_vision', 'proxy', 'display_name'): {
        "source": 'proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'proxy'),
    },
    ('ocr', 'manga_ocr', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'mit48px', '', 'description'): {
        "source": 'OCRMIT48px', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCRMIT48px'),
    },
    ('ocr', 'mit48px', 'chunk_size', 'display_name'): {
        "source": 'Chunk Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Chunk Size'),
    },
    ('ocr', 'mit48px', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'mit48px_ctc', '', 'description'): {
        "source": 'OCRMIT48px', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCRMIT48px'),
    },
    ('ocr', 'mit48px_ctc', 'chunk_size', 'display_name'): {
        "source": 'Chunk Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Chunk Size'),
    },
    ('ocr', 'mit48px_ctc', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'none_ocr', '', 'description'): {
        "source": 'Not a OCR, just return original text.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Not a OCR, just return original text.'),
    },
    ('ocr', 'none_ocr', 'NOTICE', 'display_name'): {
        "source": 'NOTICE', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'NOTICE'),
    },
    ('ocr', 'paddle_vl', '', 'description'): {
        "source": '本地部署的 Paddle OCR-VL 服务 (POST /layout-parsing)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '本地部署的 Paddle OCR-VL 服务 (POST /layout-parsing)'),
    },
    ('ocr', 'paddle_vl', 'max retry times', 'display_name'): {
        "source": 'max retry times', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max retry times'),
    },
    ('ocr', 'paddle_vl', 'prettifyMarkdown', 'display_name'): {
        "source": 'Prettify Markdown', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Prettify Markdown'),
    },
    ('ocr', 'paddle_vl', 'retry interval', 'display_name'): {
        "source": 'retry interval', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'retry interval'),
    },
    ('ocr', 'paddle_vl', 'server_url', 'display_name'): {
        "source": 'Server URL', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Server URL'),
    },
    ('ocr', 'paddle_vl', 'visualize', 'display_name'): {
        "source": 'visualize', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'visualize'),
    },
    ('ocr', 'ppv6_onnx', '', 'description'): {
        "source": 'PP-OCRv6 ONNX recognition-only — crops text blocks then recognizes via ONNX Runtime', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'PP-OCRv6 ONNX recognition-only — crops text blocks then recognizes via ONNX Runtime'),
    },
    ('ocr', 'ppv6_onnx', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'ppv6_onnx', 'rec_batch_num', 'description'): {
        "source": 'Recognition batch size (higher = faster, more VRAM)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Recognition batch size (higher = faster, more VRAM)'),
    },
    ('ocr', 'ppv6_onnx', 'rec_batch_num', 'display_name'): {
        "source": 'Recognition Batch Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Recognition Batch Size'),
    },
    ('ocr', 'stariver_ocr', '', 'description'): {
        "source": '星河云(团子翻译器) OCR API', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '星河云(团子翻译器) OCR API'),
    },
    ('ocr', 'stariver_ocr', 'Password', 'display_name'): {
        "source": 'Password', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Password'),
    },
    ('ocr', 'stariver_ocr', 'User', 'display_name'): {
        "source": 'User', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'User'),
    },
    ('ocr', 'stariver_ocr', 'detect_scale', 'display_name'): {
        "source": 'Detect Scale', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect Scale'),
    },
    ('ocr', 'stariver_ocr', 'disable_skip_area', 'display_name'): {
        "source": 'Disable Skip Area', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Disable Skip Area'),
    },
    ('ocr', 'stariver_ocr', 'filtrate', 'display_name'): {
        "source": 'Filtrate', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Filtrate'),
    },
    ('ocr', 'stariver_ocr', 'force_expand', 'description'): {
        "source": '是否强制扩展图片像素，会导致识别速度下降', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '是否强制扩展图片像素，会导致识别速度下降'),
    },
    ('ocr', 'stariver_ocr', 'force_expand', 'display_name'): {
        "source": 'Force Expand', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Force Expand'),
    },
    ('ocr', 'stariver_ocr', 'low_accuracy_mode', 'display_name'): {
        "source": 'Low Accuracy Mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Low Accuracy Mode'),
    },
    ('ocr', 'stariver_ocr', 'merge_threshold', 'display_name'): {
        "source": 'Merge Threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Merge Threshold'),
    },
    ('ocr', 'stariver_ocr', 'refine', 'display_name'): {
        "source": 'Refine', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Refine'),
    },
    ('ocr', 'stariver_ocr', 'update_token_btn', 'description'): {
        "source": '删除旧 Token 并重新申请', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '删除旧 Token 并重新申请'),
    },
    ('ocr', 'stariver_ocr', 'update_token_btn', 'display_name'): {
        "source": '更新 Token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '更新 Token'),
    },
    ('textdetector', 'ctbd', '', 'description'): {
        "source": 'RT-DETR-V2 (ogkalu/comic-text-and-bubble-detector) for text/bubble detection.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'RT-DETR-V2 (ogkalu/comic-text-and-bubble-detector) for text/bubble detection.'),
    },
    ('textdetector', 'ctbd', 'confidence_threshold', 'description'): {
        "source": 'Minimum detection score (0.0-1.0).', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Minimum detection score (0.0-1.0).'),
    },
    ('textdetector', 'ctbd', 'confidence_threshold', 'display_name'): {
        "source": 'Confidence Threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Confidence Threshold'),
    },
    ('textdetector', 'ctbd', 'containment_threshold', 'description'): {
        "source": 'Area ratio threshold to trigger removal of contained boxes (0.0-1.0).', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Area ratio threshold to trigger removal of contained boxes (0.0-1.0).'),
    },
    ('textdetector', 'ctbd', 'containment_threshold', 'display_name'): {
        "source": 'Containment Threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Containment Threshold'),
    },
    ('textdetector', 'ctbd', 'detect_bubbles', 'description'): {
        "source": 'Detect speech bubbles.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect speech bubbles.'),
    },
    ('textdetector', 'ctbd', 'detect_bubbles', 'display_name'): {
        "source": 'Detect Bubbles', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect Bubbles'),
    },
    ('textdetector', 'ctbd', 'detect_text', 'description'): {
        "source": 'Detect text blocks.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect text blocks.'),
    },
    ('textdetector', 'ctbd', 'detect_text', 'display_name'): {
        "source": 'Detect Text', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect Text'),
    },
    ('textdetector', 'ctbd', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('textdetector', 'ctbd', 'inpaint_mask_dilate', 'description'): {
        "source": 'Dilation kernel size (px) for the inpaint mask. Merges text fragments.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Dilation kernel size (px) for the inpaint mask. Merges text fragments.'),
    },
    ('textdetector', 'ctbd', 'inpaint_mask_dilate', 'display_name'): {
        "source": 'Inpaint Mask Dilate', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint Mask Dilate'),
    },
    ('textdetector', 'ctbd', 'mask_unification_method', 'description'): {
        "source": "Method to unify fragments into one mask: 'none', 'bounding rectangle', or 'convex hull'.", "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', "Method to unify fragments into one mask: 'none', 'bounding rectangle', or 'convex hull'."),
    },
    ('textdetector', 'ctbd', 'mask_unification_method', 'display_name'): {
        "source": 'Mask Unification Method', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Mask Unification Method'),
    },
    ('textdetector', 'ctbd', 'merge_duplicates', 'description'): {
        "source": 'Merge near-identical duplicate boxes of the same category.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Merge near-identical duplicate boxes of the same category.'),
    },
    ('textdetector', 'ctbd', 'merge_duplicates', 'display_name'): {
        "source": 'Merge Duplicates', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Merge Duplicates'),
    },
    ('textdetector', 'ctbd', 'merge_duplicates_iou', 'description'): {
        "source": 'IoU threshold for merging duplicates within the same class.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'IoU threshold for merging duplicates within the same class.'),
    },
    ('textdetector', 'ctbd', 'merge_duplicates_iou', 'display_name'): {
        "source": 'Merge Duplicates IoU', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Merge Duplicates IoU'),
    },
    ('textdetector', 'ctbd', 'remove_contained_text', 'description'): {
        "source": 'Remove text boxes that are largely contained within other larger text boxes.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Remove text boxes that are largely contained within other larger text boxes.'),
    },
    ('textdetector', 'ctbd', 'remove_contained_text', 'display_name'): {
        "source": 'Remove Contained Text', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Remove Contained Text'),
    },
    ('textdetector', 'ctbd', 'slice_containment_thresh', 'description'): {
        "source": 'Containment threshold for merging boxes.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Containment threshold for merging boxes.'),
    },
    ('textdetector', 'ctbd', 'slice_containment_thresh', 'display_name'): {
        "source": 'Slice Containment Threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Containment Threshold'),
    },
    ('textdetector', 'ctbd', 'slice_duplicate_iou', 'description'): {
        "source": 'IoU threshold for removing duplicate boxes.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'IoU threshold for removing duplicate boxes.'),
    },
    ('textdetector', 'ctbd', 'slice_duplicate_iou', 'display_name'): {
        "source": 'Slice Duplicate IoU', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Duplicate IoU'),
    },
    ('textdetector', 'ctbd', 'slice_merge_iou', 'description'): {
        "source": 'IoU threshold for merging text lines.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'IoU threshold for merging text lines.'),
    },
    ('textdetector', 'ctbd', 'slice_merge_iou', 'display_name'): {
        "source": 'Slice Merge IoU', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Merge IoU'),
    },
    ('textdetector', 'ctbd', 'slice_merge_y_dist', 'description'): {
        "source": 'Max relative Y-distance for merging text lines.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max relative Y-distance for merging text lines.'),
    },
    ('textdetector', 'ctbd', 'slice_merge_y_dist', 'display_name'): {
        "source": 'Slice Merge Y Distance', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Merge Y Distance'),
    },
    ('textdetector', 'ctbd', 'slice_min_height_ratio', 'description'): {
        "source": 'Minimum height ratio for the last slice.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Minimum height ratio for the last slice.'),
    },
    ('textdetector', 'ctbd', 'slice_min_height_ratio', 'display_name'): {
        "source": 'Slice Min Height Ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Min Height Ratio'),
    },
    ('textdetector', 'ctbd', 'slice_overlap_ratio', 'description'): {
        "source": 'Slice overlap ratio (0.0-1.0).', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice overlap ratio (0.0-1.0).'),
    },
    ('textdetector', 'ctbd', 'slice_overlap_ratio', 'display_name'): {
        "source": 'Slice Overlap Ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Overlap Ratio'),
    },
    ('textdetector', 'ctbd', 'slice_target_ratio', 'description'): {
        "source": 'Target H/W ratio for slices.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Target H/W ratio for slices.'),
    },
    ('textdetector', 'ctbd', 'slice_target_ratio', 'display_name'): {
        "source": 'Slice Target Ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Target Ratio'),
    },
    ('textdetector', 'ctbd', 'slice_threshold_ratio', 'description'): {
        "source": 'H/W ratio to trigger image slicing.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'H/W ratio to trigger image slicing.'),
    },
    ('textdetector', 'ctbd', 'slice_threshold_ratio', 'display_name'): {
        "source": 'Slice Threshold Ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Slice Threshold Ratio'),
    },
    ('textdetector', 'ctd', '', 'description'): {
        "source": 'ComicTextDetector', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'ComicTextDetector'),
    },
    ('textdetector', 'ctd', 'det_rearrange_max_batches', 'display_name'): {
        "source": 'Max split batch size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max split batch size'),
    },
    ('textdetector', 'ctd', 'detect_size', 'display_name'): {
        "source": 'Detect Size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect Size'),
    },
    ('textdetector', 'ctd', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('textdetector', 'ctd', 'font size max', 'display_name'): {
        "source": 'font size max', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size max'),
    },
    ('textdetector', 'ctd', 'font size min', 'display_name'): {
        "source": 'font size min', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size min'),
    },
    ('textdetector', 'ctd', 'font size multiplier', 'display_name'): {
        "source": 'font size multiplier', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size multiplier'),
    },
    ('textdetector', 'ctd', 'mask dilate size', 'display_name'): {
        "source": 'mask dilate size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'mask dilate size'),
    },
    ('textdetector', 'stariver_ocr', '', 'description'): {
        "source": '星河云(团子翻译器) OCR 文字检测器', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '星河云(团子翻译器) OCR 文字检测器'),
    },
    ('textdetector', 'stariver_ocr', 'Password', 'display_name'): {
        "source": 'Password', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Password'),
    },
    ('textdetector', 'stariver_ocr', 'User', 'display_name'): {
        "source": 'User', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'User'),
    },
    ('textdetector', 'stariver_ocr', 'detect_scale', 'display_name'): {
        "source": 'Detect Scale', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Detect Scale'),
    },
    ('textdetector', 'stariver_ocr', 'disable_skip_area', 'display_name'): {
        "source": 'Disable Skip Area', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Disable Skip Area'),
    },
    ('textdetector', 'stariver_ocr', 'expand_ratio', 'display_name'): {
        "source": 'Expand Ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Expand Ratio'),
    },
    ('textdetector', 'stariver_ocr', 'filtrate', 'display_name'): {
        "source": 'Filtrate', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Filtrate'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_max(set to -1 to disable)', 'display_name'): {
        "source": 'Font Size Max (set to -1 to disable)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Font Size Max (set to -1 to disable)'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_min(set to -1 to disable)', 'display_name'): {
        "source": 'Font Size Min (set to -1 to disable)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Font Size Min (set to -1 to disable)'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_multiplier', 'display_name'): {
        "source": 'Font Size Multiplier', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Font Size Multiplier'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_offset', 'display_name'): {
        "source": 'Font Size Offset', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Font Size Offset'),
    },
    ('textdetector', 'stariver_ocr', 'force_expand', 'display_name'): {
        "source": 'Force Expand', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Force Expand'),
    },
    ('textdetector', 'stariver_ocr', 'low_accuracy_mode', 'display_name'): {
        "source": 'Low Accuracy Mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Low Accuracy Mode'),
    },
    ('textdetector', 'stariver_ocr', 'merge_threshold', 'display_name'): {
        "source": 'Merge Threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Merge Threshold'),
    },
    ('textdetector', 'stariver_ocr', 'refine', 'display_name'): {
        "source": 'Refine', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Refine'),
    },
    ('textdetector', 'stariver_ocr', 'update_token_btn', 'description'): {
        "source": '删除旧 Token 并重新申请', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '删除旧 Token 并重新申请'),
    },
    ('textdetector', 'stariver_ocr', 'update_token_btn', 'display_name'): {
        "source": '更新 Token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '更新 Token'),
    },
    ('textdetector', 'ysgyolo', 'IoU threshold', 'display_name'): {
        "source": 'IoU阈值', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'IoU阈值'),
    },
    ('textdetector', 'ysgyolo', 'confidence threshold', 'display_name'): {
        "source": '置信度阈值', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '置信度阈值'),
    },
    ('textdetector', 'ysgyolo', 'detect size', 'display_name'): {
        "source": '检测尺寸', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '检测尺寸'),
    },
    ('textdetector', 'ysgyolo', 'device', 'display_name'): {
        "source": '设备', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '设备'),
    },
    ('textdetector', 'ysgyolo', 'font size max', 'display_name'): {
        "source": '最大字号', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '最大字号'),
    },
    ('textdetector', 'ysgyolo', 'font size min', 'display_name'): {
        "source": '最小字号', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '最小字号'),
    },
    ('textdetector', 'ysgyolo', 'font size multiplier', 'display_name'): {
        "source": '字号乘数', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '字号乘数'),
    },
    ('textdetector', 'ysgyolo', 'label', 'display_name'): {
        "source": '标签', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '标签'),
    },
    ('textdetector', 'ysgyolo', 'mask dilate size', 'display_name'): {
        "source": '掩码扩张尺寸', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '掩码扩张尺寸'),
    },
    ('textdetector', 'ysgyolo', 'merge text lines', 'display_name'): {
        "source": '合并文本行', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '合并文本行'),
    },
    ('textdetector', 'ysgyolo', 'model path', 'display_name'): {
        "source": '模型路径', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '模型路径'),
    },
    ('textdetector', 'ysgyolo', 'source text is vertical', 'display_name'): {
        "source": '竖排文本', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '竖排文本'),
    },
    ('translator', 'Baidu', 'appId', 'display_name'): {
        "source": 'appId', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'appId'),
    },
    ('translator', 'Baidu', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Baidu', 'token', 'display_name'): {
        "source": 'token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'token'),
    },
    ('translator', 'Caiyun', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Caiyun', 'token', 'display_name'): {
        "source": 'token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'token'),
    },
    ('translator', 'Copy Source', '', 'description'): {
        "source": 'Return source text as translation', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Return source text as translation'),
    },
    ('translator', 'DeepL', 'api_key', 'display_name'): {
        "source": 'API Key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API Key'),
    },
    ('translator', 'DeepL', 'context', 'display_name'): {
        "source": 'context', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'context'),
    },
    ('translator', 'DeepL', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'DeepL', 'formality', 'display_name'): {
        "source": 'formality', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'formality'),
    },
    ('translator', 'DeepL', 'preserve_formatting', 'display_name'): {
        "source": 'Preserve Formatting', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Preserve Formatting'),
    },
    ('translator', 'DeepLX API', 'api_url', 'display_name'): {
        "source": 'API URL', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API URL'),
    },
    ('translator', 'DeepLX API', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'LLMTranslator', '', 'description'): {
        "source": 'Translate using the selected text-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Translate using the selected text-capable LLM profile.'),
    },
    ('translator', 'LLMTranslator', 'delay', 'description'): {
        "source": 'Delay between LLM requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM requests in seconds.'),
    },
    ('translator', 'LLMTranslator', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('translator', 'LLMTranslator', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM translation.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM translation.'),
    },
    ('translator', 'LLMTranslator', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('translator', 'LLMTranslator', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('translator', 'LLMTranslator', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('translator', 'LLMTranslator', 'retry attempts', 'description'): {
        "source": 'Retries for API or parsing failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API or parsing failures.'),
    },
    ('translator', 'LLMTranslator', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('translator', 'LLMTranslator', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('translator', 'LLMTranslator', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('translator', 'Papago', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Sakura', 'api baseurl', 'display_name'): {
        "source": 'api baseurl', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api baseurl'),
    },
    ('translator', 'Sakura', 'dict path', 'display_name'): {
        "source": 'dict path', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'dict path'),
    },
    ('translator', 'Sakura', 'do enlarge small kana', 'description'): {
        "source": 'Enlarge small kana to normal size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Enlarge small kana to normal size'),
    },
    ('translator', 'Sakura', 'do enlarge small kana', 'display_name'): {
        "source": 'do enlarge small kana', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'do enlarge small kana'),
    },
    ('translator', 'Sakura', 'force apply dict', 'description'): {
        "source": 'Force apply the dictionary regardless of whether the terms appear in the original text\n DO NOT CHECK THIS IF YOU ARE NOT SURE WHAT IT MEANS', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Force apply the dictionary regardless of whether the terms appear in the original text\n DO NOT CHECK THIS IF YOU ARE NOT SURE WHAT IT MEANS'),
    },
    ('translator', 'Sakura', 'force apply dict', 'display_name'): {
        "source": 'force apply dict', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'force apply dict'),
    },
    ('translator', 'Sakura', 'low vram mode', 'description'): {
        "source": "check it if you're running it locally on a single device and encountered a crash due to vram OOM", "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', "check it if you're running it locally on a single device and encountered a crash due to vram OOM"),
    },
    ('translator', 'Sakura', 'low vram mode', 'display_name'): {
        "source": 'low vram mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'low vram mode'),
    },
    ('translator', 'Sakura', 'max tokens', 'display_name'): {
        "source": 'max tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max tokens'),
    },
    ('translator', 'Sakura', 'repeat detect threshold', 'display_name'): {
        "source": 'repeat detect threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'repeat detect threshold'),
    },
    ('translator', 'Sakura', 'retry attempts', 'display_name'): {
        "source": 'retry attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'retry attempts'),
    },
    ('translator', 'Sakura', 'timeout', 'display_name'): {
        "source": 'timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'timeout'),
    },
    ('translator', 'Sakura', 'version', 'display_name'): {
        "source": 'version', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'version'),
    },
    ('translator', 'Sugoi', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('translator', 'Yandex', 'api_key', 'display_name'): {
        "source": 'API Key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API Key'),
    },
    ('translator', 'Yandex', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Yandex-FOSWLY', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Yandex-FOSWLY', 'service', 'description'): {
        "source": 'Select the translation service from the FOSWLY library.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Select the translation service from the FOSWLY library.'),
    },
    ('translator', 'Yandex-FOSWLY', 'service', 'display_name'): {
        "source": 'service', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'service'),
    },
    ('translator', 'Yandex-FOSWLY', 'yandex_cloud_api_key', 'description'): {
        "source": 'API Key for Yandex.Cloud. If empty, a keyless method will be attempted.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API Key for Yandex.Cloud. If empty, a keyless method will be attempted.'),
    },
    ('translator', 'Yandex-FOSWLY', 'yandex_cloud_api_key', 'display_name'): {
        "source": 'Yandex Cloud API Key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Yandex Cloud API Key'),
    },
    ('translator', 'ezTrans', 'path_dat', 'display_name'): {
        "source": 'DAT Path', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'DAT Path'),
    },
    ('translator', 'ezTrans', 'path_j2k(J2KEngine.dll)', 'display_name'): {
        "source": 'J2KEngine.dll Path', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'J2KEngine.dll Path'),
    },
    ('translator', 'ezTrans', 'path_k2j(ehnd-kor.dll, Optional)', 'display_name'): {
        "source": 'ehnd-kor.dll Path (optional)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'ehnd-kor.dll Path (optional)'),
    },
    ('translator', 'google', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'm2m100', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
}
