# This file is auto-generated by scripts/update_translation.py.
# Do not edit by hand; rerun the script after changing module parameter metadata.

from qtpy.QtCore import QCoreApplication

MODULE_PARAM_CATALOG = {
    ('inpainter', 'LLMInpaint', '', 'description'): {
        "source": 'Inpaint using the selected image-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint using the selected image-capable LLM profile.'),
    },
    ('inpainter', 'LLMInpaint', 'delay', 'description'): {
        "source": 'Delay between LLM image cleanup requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM image cleanup requests in seconds.'),
    },
    ('inpainter', 'LLMInpaint', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('inpainter', 'LLMInpaint', 'inpaint by block', 'description'): {
        "source": 'Send each text block crop separately instead of sending the whole image.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Send each text block crop separately instead of sending the whole image.'),
    },
    ('inpainter', 'LLMInpaint', 'inpaint by block', 'display_name'): {
        "source": 'Inpaint By Block', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Inpaint By Block'),
    },
    ('inpainter', 'LLMInpaint', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM image cleanup.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM image cleanup.'),
    },
    ('inpainter', 'LLMInpaint', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('inpainter', 'LLMInpaint', 'max resolution', 'description'): {
        "source": 'Scale images down before sending them to the LLM. Set to 0 to keep the original size.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Scale images down before sending them to the LLM. Set to 0 to keep the original size.'),
    },
    ('inpainter', 'LLMInpaint', 'max resolution', 'display_name'): {
        "source": 'Max Resolution', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Resolution'),
    },
    ('inpainter', 'LLMInpaint', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('inpainter', 'LLMInpaint', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('inpainter', 'LLMInpaint', 'request timeout', 'description'): {
        "source": 'HTTP timeout for image cleanup requests in seconds. Set to 0 to disable.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'HTTP timeout for image cleanup requests in seconds. Set to 0 to disable.'),
    },
    ('inpainter', 'LLMInpaint', 'request timeout', 'display_name'): {
        "source": 'Request Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Request Timeout'),
    },
    ('inpainter', 'LLMInpaint', 'retry attempts', 'description'): {
        "source": 'Retries for API failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API failures.'),
    },
    ('inpainter', 'LLMInpaint', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('inpainter', 'LLMInpaint', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('inpainter', 'LLMInpaint', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('inpainter', 'aot', '', 'description'): {
        "source": 'manga-image-translator inpainter', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'manga-image-translator inpainter'),
    },
    ('inpainter', 'aot', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'aot', 'inpaint_size', 'display_name'): {
        "source": 'inpaint_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'inpaint_size'),
    },
    ('inpainter', 'flux2-klein', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'flux2-klein', 'max_resolution', 'display_name'): {
        "source": 'max_resolution', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max_resolution'),
    },
    ('inpainter', 'flux2-klein', 'model', 'display_name'): {
        "source": 'model', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'model'),
    },
    ('inpainter', 'flux2-klein', 'step', 'display_name'): {
        "source": 'step', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'step'),
    },
    ('inpainter', 'lama_large_512px', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'lama_large_512px', 'inpaint_size', 'display_name'): {
        "source": 'inpaint_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'inpaint_size'),
    },
    ('inpainter', 'lama_large_512px', 'precision', 'display_name'): {
        "source": 'precision', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'precision'),
    },
    ('inpainter', 'lama_mpe', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('inpainter', 'lama_mpe', 'inpaint_size', 'display_name'): {
        "source": 'inpaint_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'inpaint_size'),
    },
    ('ocr', 'LLMOCR', '', 'description'): {
        "source": 'OCR using the selected vision-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using the selected vision-capable LLM profile.'),
    },
    ('ocr', 'LLMOCR', 'delay', 'description'): {
        "source": 'Delay between LLM OCR requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM OCR requests in seconds.'),
    },
    ('ocr', 'LLMOCR', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('ocr', 'LLMOCR', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM OCR.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM OCR.'),
    },
    ('ocr', 'LLMOCR', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('ocr', 'LLMOCR', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('ocr', 'LLMOCR', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('ocr', 'LLMOCR', 'retry attempts', 'description'): {
        "source": 'Retries for API failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API failures.'),
    },
    ('ocr', 'LLMOCR', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('ocr', 'LLMOCR', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('ocr', 'LLMOCR', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('ocr', 'PaddleOCRVLManga', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'PaddleOCRVLManga', 'max_new_tokens', 'description'): {
        "source": 'Max generation tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max generation tokens'),
    },
    ('ocr', 'PaddleOCRVLManga', 'max_new_tokens', 'display_name'): {
        "source": 'max_new_tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max_new_tokens'),
    },
    ('ocr', 'google_lens_exp', '', 'description'): {
        "source": 'OCR using Google Lens Protobuf API (requests backend)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using Google Lens Protobuf API (requests backend)'),
    },
    ('ocr', 'google_lens_exp', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('ocr', 'google_lens_exp', 'newline_handling', 'description'): {
        "source": 'Handle newline characters in the final OCR string.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Handle newline characters in the final OCR string.'),
    },
    ('ocr', 'google_lens_exp', 'newline_handling', 'display_name'): {
        "source": 'newline_handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'newline_handling'),
    },
    ('ocr', 'google_lens_exp', 'no_uppercase', 'description'): {
        "source": 'Convert text to lowercase except first letter of sentences.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Convert text to lowercase except first letter of sentences.'),
    },
    ('ocr', 'google_lens_exp', 'no_uppercase', 'display_name'): {
        "source": 'no_uppercase', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'no_uppercase'),
    },
    ('ocr', 'google_lens_exp', 'proxy', 'description'): {
        "source": 'Proxy (requests format: e.g., http://user:pass@host:port or {"http": ..., "https": ...})', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy (requests format: e.g., http://user:pass@host:port or {"http": ..., "https": ...})'),
    },
    ('ocr', 'google_lens_exp', 'proxy', 'display_name'): {
        "source": 'proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'proxy'),
    },
    ('ocr', 'google_lens_exp', 'target_language', 'description'): {
        "source": "Target language code (e.g., 'ja', 'en', 'ru').", "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', "Target language code (e.g., 'ja', 'en', 'ru')."),
    },
    ('ocr', 'google_lens_exp', 'target_language', 'display_name'): {
        "source": 'target_language', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'target_language'),
    },
    ('ocr', 'google_screen_ai_ocr', '', 'description'): {
        "source": 'Google ScreenAI OCR engine. Automatically downloads files on module load.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Google ScreenAI OCR engine. Automatically downloads files on module load.'),
    },
    ('ocr', 'google_screen_ai_ocr', 'light_mode', 'description'): {
        "source": 'Use the faster, lighter ScreenAI OCR model', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Use the faster, lighter ScreenAI OCR model'),
    },
    ('ocr', 'google_screen_ai_ocr', 'light_mode', 'display_name'): {
        "source": 'Light Mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Light Mode'),
    },
    ('ocr', 'google_screen_ai_ocr', 'newline_handling', 'description'): {
        "source": 'Choose how to handle newline characters in OCR results', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Choose how to handle newline characters in OCR results'),
    },
    ('ocr', 'google_screen_ai_ocr', 'newline_handling', 'display_name'): {
        "source": 'Newline Handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Newline Handling'),
    },
    ('ocr', 'google_vision', '', 'description'): {
        "source": 'OCR using Google Vision API', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCR using Google Vision API'),
    },
    ('ocr', 'google_vision', 'api_key', 'display_name'): {
        "source": 'api_key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api_key'),
    },
    ('ocr', 'google_vision', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('ocr', 'google_vision', 'language_hints', 'description'): {
        "source": 'Language codes separated by commas (BCP-47)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Language codes separated by commas (BCP-47)'),
    },
    ('ocr', 'google_vision', 'language_hints', 'display_name'): {
        "source": 'language_hints', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'language_hints'),
    },
    ('ocr', 'google_vision', 'newline_handling', 'description'): {
        "source": 'Choose how to handle newline characters in OCR results', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Choose how to handle newline characters in OCR results'),
    },
    ('ocr', 'google_vision', 'newline_handling', 'display_name'): {
        "source": 'newline_handling', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'newline_handling'),
    },
    ('ocr', 'google_vision', 'no_uppercase', 'description'): {
        "source": 'Convert text to lowercase except the first letter of each sentence', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Convert text to lowercase except the first letter of each sentence'),
    },
    ('ocr', 'google_vision', 'no_uppercase', 'display_name'): {
        "source": 'no_uppercase', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'no_uppercase'),
    },
    ('ocr', 'google_vision', 'proxy', 'description'): {
        "source": 'Proxy address (e.g., http(s)://user:password@host:port or socks4/5://user:password@host:port)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address (e.g., http(s)://user:password@host:port or socks4/5://user:password@host:port)'),
    },
    ('ocr', 'google_vision', 'proxy', 'display_name'): {
        "source": 'proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'proxy'),
    },
    ('ocr', 'manga_ocr', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'mit48px', '', 'description'): {
        "source": 'OCRMIT48px', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCRMIT48px'),
    },
    ('ocr', 'mit48px', 'chunk_size', 'display_name'): {
        "source": 'chunk_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'chunk_size'),
    },
    ('ocr', 'mit48px', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'mit48px_ctc', '', 'description'): {
        "source": 'OCRMIT48px', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'OCRMIT48px'),
    },
    ('ocr', 'mit48px_ctc', 'chunk_size', 'display_name'): {
        "source": 'chunk_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'chunk_size'),
    },
    ('ocr', 'mit48px_ctc', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'none_ocr', '', 'description'): {
        "source": 'Not a OCR, just return original text.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Not a OCR, just return original text.'),
    },
    ('ocr', 'none_ocr', 'NOTICE', 'display_name'): {
        "source": 'NOTICE', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'NOTICE'),
    },
    ('ocr', 'paddle_vl', '', 'description'): {
        "source": '本地部署的 Paddle OCR-VL 服务 (POST /layout-parsing)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '本地部署的 Paddle OCR-VL 服务 (POST /layout-parsing)'),
    },
    ('ocr', 'paddle_vl', 'max retry times', 'display_name'): {
        "source": 'max retry times', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max retry times'),
    },
    ('ocr', 'paddle_vl', 'prettifyMarkdown', 'display_name'): {
        "source": 'prettifyMarkdown', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'prettifyMarkdown'),
    },
    ('ocr', 'paddle_vl', 'retry interval', 'display_name'): {
        "source": 'retry interval', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'retry interval'),
    },
    ('ocr', 'paddle_vl', 'server_url', 'display_name'): {
        "source": 'server_url', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'server_url'),
    },
    ('ocr', 'paddle_vl', 'visualize', 'display_name'): {
        "source": 'visualize', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'visualize'),
    },
    ('ocr', 'ppv6_onnx', '', 'description'): {
        "source": 'PP-OCRv6 ONNX recognition-only — crops text blocks then recognizes via ONNX Runtime', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'PP-OCRv6 ONNX recognition-only — crops text blocks then recognizes via ONNX Runtime'),
    },
    ('ocr', 'ppv6_onnx', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('ocr', 'ppv6_onnx', 'rec_batch_num', 'description'): {
        "source": 'Recognition batch size (higher = faster, more VRAM)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Recognition batch size (higher = faster, more VRAM)'),
    },
    ('ocr', 'ppv6_onnx', 'rec_batch_num', 'display_name'): {
        "source": 'rec_batch_num', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'rec_batch_num'),
    },
    ('ocr', 'stariver_ocr', '', 'description'): {
        "source": '星河云(团子翻译器) OCR API', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '星河云(团子翻译器) OCR API'),
    },
    ('ocr', 'stariver_ocr', 'Password', 'display_name'): {
        "source": 'Password', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Password'),
    },
    ('ocr', 'stariver_ocr', 'User', 'display_name'): {
        "source": 'User', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'User'),
    },
    ('ocr', 'stariver_ocr', 'detect_scale', 'display_name'): {
        "source": 'detect_scale', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'detect_scale'),
    },
    ('ocr', 'stariver_ocr', 'disable_skip_area', 'display_name'): {
        "source": 'disable_skip_area', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'disable_skip_area'),
    },
    ('ocr', 'stariver_ocr', 'filtrate', 'display_name'): {
        "source": 'filtrate', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'filtrate'),
    },
    ('ocr', 'stariver_ocr', 'force_expand', 'description'): {
        "source": '是否强制扩展图片像素，会导致识别速度下降', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '是否强制扩展图片像素，会导致识别速度下降'),
    },
    ('ocr', 'stariver_ocr', 'force_expand', 'display_name'): {
        "source": 'force_expand', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'force_expand'),
    },
    ('ocr', 'stariver_ocr', 'low_accuracy_mode', 'display_name'): {
        "source": 'low_accuracy_mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'low_accuracy_mode'),
    },
    ('ocr', 'stariver_ocr', 'merge_threshold', 'display_name'): {
        "source": 'merge_threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'merge_threshold'),
    },
    ('ocr', 'stariver_ocr', 'refine', 'display_name'): {
        "source": 'refine', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'refine'),
    },
    ('ocr', 'stariver_ocr', 'update_token_btn', 'description'): {
        "source": '删除旧 Token 并重新申请', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '删除旧 Token 并重新申请'),
    },
    ('ocr', 'stariver_ocr', 'update_token_btn', 'display_name'): {
        "source": '更新 Token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '更新 Token'),
    },
    ('textdetector', 'ctd', '', 'description'): {
        "source": 'ComicTextDetector', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'ComicTextDetector'),
    },
    ('textdetector', 'ctd', 'det_rearrange_max_batches', 'display_name'): {
        "source": 'det_rearrange_max_batches', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'det_rearrange_max_batches'),
    },
    ('textdetector', 'ctd', 'detect_size', 'display_name'): {
        "source": 'detect_size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'detect_size'),
    },
    ('textdetector', 'ctd', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('textdetector', 'ctd', 'font size max', 'display_name'): {
        "source": 'font size max', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size max'),
    },
    ('textdetector', 'ctd', 'font size min', 'display_name'): {
        "source": 'font size min', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size min'),
    },
    ('textdetector', 'ctd', 'font size multiplier', 'display_name'): {
        "source": 'font size multiplier', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font size multiplier'),
    },
    ('textdetector', 'ctd', 'mask dilate size', 'display_name'): {
        "source": 'mask dilate size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'mask dilate size'),
    },
    ('textdetector', 'stariver_ocr', '', 'description'): {
        "source": '星河云(团子翻译器) OCR 文字检测器', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '星河云(团子翻译器) OCR 文字检测器'),
    },
    ('textdetector', 'stariver_ocr', 'Password', 'display_name'): {
        "source": 'Password', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Password'),
    },
    ('textdetector', 'stariver_ocr', 'User', 'display_name'): {
        "source": 'User', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'User'),
    },
    ('textdetector', 'stariver_ocr', 'detect_scale', 'display_name'): {
        "source": 'detect_scale', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'detect_scale'),
    },
    ('textdetector', 'stariver_ocr', 'disable_skip_area', 'display_name'): {
        "source": 'disable_skip_area', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'disable_skip_area'),
    },
    ('textdetector', 'stariver_ocr', 'expand_ratio', 'display_name'): {
        "source": 'expand_ratio', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'expand_ratio'),
    },
    ('textdetector', 'stariver_ocr', 'filtrate', 'display_name'): {
        "source": 'filtrate', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'filtrate'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_max(set to -1 to disable)', 'display_name'): {
        "source": 'font_size_max(set to -1 to disable)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font_size_max(set to -1 to disable)'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_min(set to -1 to disable)', 'display_name'): {
        "source": 'font_size_min(set to -1 to disable)', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font_size_min(set to -1 to disable)'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_multiplier', 'display_name'): {
        "source": 'font_size_multiplier', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font_size_multiplier'),
    },
    ('textdetector', 'stariver_ocr', 'font_size_offset', 'display_name'): {
        "source": 'font_size_offset', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'font_size_offset'),
    },
    ('textdetector', 'stariver_ocr', 'force_expand', 'display_name'): {
        "source": 'force_expand', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'force_expand'),
    },
    ('textdetector', 'stariver_ocr', 'low_accuracy_mode', 'display_name'): {
        "source": 'low_accuracy_mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'low_accuracy_mode'),
    },
    ('textdetector', 'stariver_ocr', 'merge_threshold', 'display_name'): {
        "source": 'merge_threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'merge_threshold'),
    },
    ('textdetector', 'stariver_ocr', 'refine', 'display_name'): {
        "source": 'refine', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'refine'),
    },
    ('textdetector', 'stariver_ocr', 'update_token_btn', 'description'): {
        "source": '删除旧 Token 并重新申请', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '删除旧 Token 并重新申请'),
    },
    ('textdetector', 'stariver_ocr', 'update_token_btn', 'display_name'): {
        "source": '更新 Token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '更新 Token'),
    },
    ('textdetector', 'ysgyolo', 'IoU threshold', 'display_name'): {
        "source": 'IoU阈值', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'IoU阈值'),
    },
    ('textdetector', 'ysgyolo', 'confidence threshold', 'display_name'): {
        "source": '置信度阈值', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '置信度阈值'),
    },
    ('textdetector', 'ysgyolo', 'detect size', 'display_name'): {
        "source": '检测尺寸', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '检测尺寸'),
    },
    ('textdetector', 'ysgyolo', 'device', 'display_name'): {
        "source": '设备', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '设备'),
    },
    ('textdetector', 'ysgyolo', 'font size max', 'display_name'): {
        "source": '最大字号', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '最大字号'),
    },
    ('textdetector', 'ysgyolo', 'font size min', 'display_name'): {
        "source": '最小字号', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '最小字号'),
    },
    ('textdetector', 'ysgyolo', 'font size multiplier', 'display_name'): {
        "source": '字号乘数', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '字号乘数'),
    },
    ('textdetector', 'ysgyolo', 'label', 'display_name'): {
        "source": '标签', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '标签'),
    },
    ('textdetector', 'ysgyolo', 'mask dilate size', 'display_name'): {
        "source": '掩码扩张尺寸', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '掩码扩张尺寸'),
    },
    ('textdetector', 'ysgyolo', 'merge text lines', 'display_name'): {
        "source": '合并文本行', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '合并文本行'),
    },
    ('textdetector', 'ysgyolo', 'model path', 'display_name'): {
        "source": '模型路径', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '模型路径'),
    },
    ('textdetector', 'ysgyolo', 'source text is vertical', 'display_name'): {
        "source": '竖排文本', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', '竖排文本'),
    },
    ('translator', 'Baidu', 'appId', 'display_name'): {
        "source": 'appId', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'appId'),
    },
    ('translator', 'Baidu', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Baidu', 'token', 'display_name'): {
        "source": 'token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'token'),
    },
    ('translator', 'Caiyun', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Caiyun', 'token', 'display_name'): {
        "source": 'token', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'token'),
    },
    ('translator', 'Copy Source', '', 'description'): {
        "source": 'Return source text as translation', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Return source text as translation'),
    },
    ('translator', 'DeepL', 'api_key', 'display_name'): {
        "source": 'api_key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api_key'),
    },
    ('translator', 'DeepL', 'context', 'display_name'): {
        "source": 'context', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'context'),
    },
    ('translator', 'DeepL', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'DeepL', 'formality', 'display_name'): {
        "source": 'formality', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'formality'),
    },
    ('translator', 'DeepL', 'preserve_formatting', 'display_name'): {
        "source": 'preserve_formatting', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'preserve_formatting'),
    },
    ('translator', 'DeepLX API', 'api_url', 'display_name'): {
        "source": 'api_url', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api_url'),
    },
    ('translator', 'DeepLX API', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'LLMTranslator', '', 'description'): {
        "source": 'Translate using the selected text-capable LLM profile.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Translate using the selected text-capable LLM profile.'),
    },
    ('translator', 'LLMTranslator', 'delay', 'description'): {
        "source": 'Delay between LLM requests in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between LLM requests in seconds.'),
    },
    ('translator', 'LLMTranslator', 'delay', 'display_name'): {
        "source": 'Delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay'),
    },
    ('translator', 'LLMTranslator', 'max requests per minute', 'description'): {
        "source": 'Global request limit for LLM translation.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Global request limit for LLM translation.'),
    },
    ('translator', 'LLMTranslator', 'max requests per minute', 'display_name'): {
        "source": 'Max Requests Per Minute', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Max Requests Per Minute'),
    },
    ('translator', 'LLMTranslator', 'proxy', 'description'): {
        "source": 'Proxy address used for the OpenAI-compatible client.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy address used for the OpenAI-compatible client.'),
    },
    ('translator', 'LLMTranslator', 'proxy', 'display_name'): {
        "source": 'Proxy', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Proxy'),
    },
    ('translator', 'LLMTranslator', 'retry attempts', 'description'): {
        "source": 'Retries for API or parsing failures.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retries for API or parsing failures.'),
    },
    ('translator', 'LLMTranslator', 'retry attempts', 'display_name'): {
        "source": 'Retry Attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Attempts'),
    },
    ('translator', 'LLMTranslator', 'retry timeout', 'description'): {
        "source": 'Delay between retries in seconds.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Delay between retries in seconds.'),
    },
    ('translator', 'LLMTranslator', 'retry timeout', 'display_name'): {
        "source": 'Retry Timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Retry Timeout'),
    },
    ('translator', 'Papago', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Sakura', 'api baseurl', 'display_name'): {
        "source": 'api baseurl', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api baseurl'),
    },
    ('translator', 'Sakura', 'dict path', 'display_name'): {
        "source": 'dict path', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'dict path'),
    },
    ('translator', 'Sakura', 'do enlarge small kana', 'description'): {
        "source": 'Enlarge small kana to normal size', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Enlarge small kana to normal size'),
    },
    ('translator', 'Sakura', 'do enlarge small kana', 'display_name'): {
        "source": 'do enlarge small kana', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'do enlarge small kana'),
    },
    ('translator', 'Sakura', 'force apply dict', 'description'): {
        "source": 'Force apply the dictionary regardless of whether the terms appear in the original text\n DO NOT CHECK THIS IF YOU ARE NOT SURE WHAT IT MEANS', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Force apply the dictionary regardless of whether the terms appear in the original text\n DO NOT CHECK THIS IF YOU ARE NOT SURE WHAT IT MEANS'),
    },
    ('translator', 'Sakura', 'force apply dict', 'display_name'): {
        "source": 'force apply dict', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'force apply dict'),
    },
    ('translator', 'Sakura', 'low vram mode', 'description'): {
        "source": "check it if you're running it locally on a single device and encountered a crash due to vram OOM", "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', "check it if you're running it locally on a single device and encountered a crash due to vram OOM"),
    },
    ('translator', 'Sakura', 'low vram mode', 'display_name'): {
        "source": 'low vram mode', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'low vram mode'),
    },
    ('translator', 'Sakura', 'max tokens', 'display_name'): {
        "source": 'max tokens', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'max tokens'),
    },
    ('translator', 'Sakura', 'repeat detect threshold', 'display_name'): {
        "source": 'repeat detect threshold', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'repeat detect threshold'),
    },
    ('translator', 'Sakura', 'retry attempts', 'display_name'): {
        "source": 'retry attempts', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'retry attempts'),
    },
    ('translator', 'Sakura', 'timeout', 'display_name'): {
        "source": 'timeout', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'timeout'),
    },
    ('translator', 'Sakura', 'version', 'display_name'): {
        "source": 'version', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'version'),
    },
    ('translator', 'Sugoi', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
    ('translator', 'Yandex', 'api_key', 'display_name'): {
        "source": 'api_key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'api_key'),
    },
    ('translator', 'Yandex', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Yandex-FOSWLY', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'Yandex-FOSWLY', 'service', 'description'): {
        "source": 'Select the translation service from the FOSWLY library.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'Select the translation service from the FOSWLY library.'),
    },
    ('translator', 'Yandex-FOSWLY', 'service', 'display_name'): {
        "source": 'service', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'service'),
    },
    ('translator', 'Yandex-FOSWLY', 'yandex_cloud_api_key', 'description'): {
        "source": 'API Key for Yandex.Cloud. If empty, a keyless method will be attempted.', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'API Key for Yandex.Cloud. If empty, a keyless method will be attempted.'),
    },
    ('translator', 'Yandex-FOSWLY', 'yandex_cloud_api_key', 'display_name'): {
        "source": 'yandex_cloud_api_key', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'yandex_cloud_api_key'),
    },
    ('translator', 'google', 'delay', 'display_name'): {
        "source": 'delay', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'delay'),
    },
    ('translator', 'm2m100', 'device', 'display_name'): {
        "source": 'device', "translate": lambda: QCoreApplication.translate('ModuleParamTranslator', 'device'),
    },
}
