# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: view_hierarchy.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'view_hierarchy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14view_hierarchy.proto\x12\x08screenai\"G\n\x0b\x42oundingBox\x12\x0b\n\x03top\x18\x01 \x01(\x02\x12\x0c\n\x04left\x18\x02 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x02\x12\r\n\x05right\x18\x04 \x01(\x02\"M\n\x11\x42oundingBoxPixels\x12\x0b\n\x03top\x18\x01 \x01(\x05\x12\x0c\n\x04left\x18\x02 \x01(\x05\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x05\x12\r\n\x05right\x18\x04 \x01(\x05\"?\n\rViewHierarchy\x12(\n\x0bui_elements\x18\x02 \x03(\x0b\x32\x13.screenai.UiElementJ\x04\x08\x01\x10\x02\"\xb4\x02\n\tUiElement\x12\x0e\n\x02id\x18\x01 \x01(\x05:\x02-1\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.screenai.UiElementType\x12\x15\n\tparent_id\x18\x03 \x01(\x05:\x02-1\x12\x15\n\tchild_ids\x18\x04 \x03(\x05\x42\x02\x10\x01\x12+\n\x0c\x62ounding_box\x18\x06 \x01(\x0b\x32\x15.screenai.BoundingBox\x12\x38\n\x13\x62ounding_box_pixels\x18\x08 \x01(\x0b\x32\x1b.screenai.BoundingBoxPixels\x12\x30\n\nattributes\x18\x07 \x03(\x0b\x32\x1c.screenai.UiElementAttribute\x12)\n\x0b\x63hrome_info\x18\t \x01(\x0b\x32\x14.screenai.ChromeInfo\"\x96\x02\n\x12UiElementAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x05 \x01(\x02H\x00\x12+\n\x0eint_list_value\x18\x06 \x01(\x0b\x32\x11.screenai.IntListH\x00\x12\x31\n\x11string_list_value\x18\x07 \x01(\x0b\x32\x14.screenai.StringListH\x00\x12/\n\x10\x66loat_list_value\x18\x08 \x01(\x0b\x32\x13.screenai.FloatListH\x00\x42\x07\n\x05value\"\x1c\n\x07IntList\x12\x11\n\x05value\x18\x01 \x03(\x05\x42\x02\x10\x01\"\x1b\n\nStringList\x12\r\n\x05value\x18\x01 \x03(\t\"\x1a\n\tFloatList\x12\r\n\x05value\x18\x01 \x03(\x02\"%\n\nChromeInfo\x12\x17\n\x0b\x64om_node_id\x18\x01 \x01(\x05:\x02-1*<\n\rUiElementType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04ROOT\x10\x01\x12\n\n\x06WINDOW\x10\x02\x12\x08\n\x04VIEW\x10\x03\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'view_hierarchy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_UIELEMENT'].fields_by_name['child_ids']._loaded_options = None
  _globals['_UIELEMENT'].fields_by_name['child_ids']._serialized_options = b'\020\001'
  _globals['_INTLIST'].fields_by_name['value']._loaded_options = None
  _globals['_INTLIST'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_UIELEMENTTYPE']._serialized_start=969
  _globals['_UIELEMENTTYPE']._serialized_end=1029
  _globals['_BOUNDINGBOX']._serialized_start=34
  _globals['_BOUNDINGBOX']._serialized_end=105
  _globals['_BOUNDINGBOXPIXELS']._serialized_start=107
  _globals['_BOUNDINGBOXPIXELS']._serialized_end=184
  _globals['_VIEWHIERARCHY']._serialized_start=186
  _globals['_VIEWHIERARCHY']._serialized_end=249
  _globals['_UIELEMENT']._serialized_start=252
  _globals['_UIELEMENT']._serialized_end=560
  _globals['_UIELEMENTATTRIBUTE']._serialized_start=563
  _globals['_UIELEMENTATTRIBUTE']._serialized_end=841
  _globals['_INTLIST']._serialized_start=843
  _globals['_INTLIST']._serialized_end=871
  _globals['_STRINGLIST']._serialized_start=873
  _globals['_STRINGLIST']._serialized_end=900
  _globals['_FLOATLIST']._serialized_start=902
  _globals['_FLOATLIST']._serialized_end=928
  _globals['_CHROMEINFO']._serialized_start=930
  _globals['_CHROMEINFO']._serialized_end=967
# @@protoc_insertion_point(module_scope)
