import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, Iterable, Tuple

from qtpy.QtCore import QLocale


SYSLANG = QLocale.system().name()
TRANSLATION_CONTEXT = 'ModuleParamDialog'
GENERATED_CATALOG_PATH = Path(
    'ballontranslator/ui/_generated/module_param_dialog_i18n_catalog.py'
)
ModuleParamKey = Tuple[str, str, str, str]


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description='Update Qt translation sources.')
    parser.add_argument(
        'language_code',
        nargs='?',
        help='Language code to update, for example zh_CN. Defaults to the system locale.',
    )
    parser.add_argument(
        '--lang',
        '--language',
        dest='language_code_override',
        help='Language code to update. Overrides the positional language code.',
    )
    return parser.parse_args(argv)


def resolve_language_code(args) -> str:
    return args.language_code_override or args.language_code or SYSLANG


def _source_text(value) -> str:
    if isinstance(value, str):
        return value
    return ''


def collect_module_param_sources(specs: Iterable) -> Dict[ModuleParamKey, str]:
    """Collect extractor-visible module parameter strings from lazy metadata.

    Example:
        >>> from ballontranslator.utils.registry import ModuleSpec
        >>> spec = ModuleSpec(
        ...     key='demo',
        ...     import_path='demo',
        ...     class_name='Demo',
        ...     module_type='translator',
        ...     params={'delay': {'value': 0.0, 'display_name': 'Delay', 'description': 'Wait.'}},
        ... )
        >>> collect_module_param_sources([spec])[
        ...     ('translator', 'demo', 'delay', 'display_name')
        ... ]
        'Delay'
    """

    sources: Dict[ModuleParamKey, str] = {}
    for spec in specs:
        module_type = _source_text(getattr(spec, 'module_type', ''))
        module_key = _source_text(getattr(spec, 'key', ''))
        params = getattr(spec, 'params', None)
        if not module_type or not module_key or not isinstance(params, dict):
            continue

        description = _source_text(params.get('description'))
        if description:
            sources[(module_type, module_key, '', 'description')] = description

        for param_key, param in params.items():
            if not isinstance(param_key, str) or param_key == 'description' or param_key.startswith('__'):
                continue
            display_name = param_key
            param_description = ''
            if isinstance(param, dict):
                display_name = _source_text(param.get('display_name')) or param_key
                param_description = _source_text(param.get('description'))

            if display_name:
                sources[(module_type, module_key, param_key, 'display_name')] = display_name
            if param_description:
                sources[(module_type, module_key, param_key, 'description')] = param_description
    return dict(sorted(sources.items()))


def _format_key(key: ModuleParamKey) -> str:
    module_type, module_key, param_key, field = key
    return f'({module_type!r}, {module_key!r}, {param_key!r}, {field!r})'


def build_generated_catalog_source(sources: Dict[ModuleParamKey, str]) -> str:
    lines = [
        '# This file is auto-generated by scripts/update_translation.py.',
        '# Do not edit by hand; rerun the script after changing module parameter metadata.',
        '',
        'from qtpy.QtCore import QCoreApplication',
        '',
        'MODULE_PARAM_CATALOG = {',
    ]
    for key, source in sorted(sources.items()):
        lines.extend([
            f'    {_format_key(key)}: {{',
            f'        "source": {source!r}, "translate": lambda: QCoreApplication.translate({TRANSLATION_CONTEXT!r}, {source!r}),',
            '    },',
        ])
    lines.extend([
        '}',
        '',
    ])
    return '\n'.join(lines)


def write_module_param_catalog(output_path: Path, sources: Dict[ModuleParamKey, str]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w', encoding='utf8', newline='\n') as output_file:
        output_file.write(build_generated_catalog_source(sources))


def _iter_lazy_module_specs(program_dir: Path):
    if str(program_dir) not in sys.path:
        sys.path.insert(0, str(program_dir))
    os.environ.setdefault('BALLOONTRANS_APP_ROOT', str(program_dir))

    from ballontranslator.modules.lazy_registry import iter_lazy_module_specs

    yield from iter_lazy_module_specs(include_inactive_platform_branches=True)


def generate_module_param_catalog(program_dir: Path) -> Path:
    output_path = program_dir / GENERATED_CATALOG_PATH
    sources = collect_module_param_sources(_iter_lazy_module_specs(program_dir))
    write_module_param_catalog(output_path, sources)
    return output_path


def _ui_python_files(program_dir: Path):
    ui_dir = program_dir / 'ballontranslator' / 'ui'
    return [str(path) for path in sorted(ui_dir.rglob('*.py'))]


def run_lupdate(program_dir: Path, translate_path: Path) -> None:
    environment_bin = Path(sys.executable).resolve().parent
    candidates = ('pyside6-lupdate', 'pylupdate6', 'pylupdate5')
    lupdate = next(
        (
            str(environment_bin / name)
            for name in candidates
            if (environment_bin / name).is_file()
        ),
        None,
    )
    if lupdate is None:
        lupdate = next(
            (shutil.which(name) for name in candidates if shutil.which(name)),
            None,
        )
    if lupdate is None:
        raise SystemExit('No Python-capable Qt lupdate executable was found.')
    command = [lupdate, '-verbose', *_ui_python_files(program_dir), '-ts', str(translate_path)]
    subprocess.run(command, check=True)


if __name__ == '__main__':
    args = parse_args()
    language_code = resolve_language_code(args)
    program_dir = Path(__file__).resolve().parents[1]
    translate_dir = program_dir / 'resources' / 'translate'
    translate_path = translate_dir / f'{language_code}.ts'

    catalog_path = generate_module_param_catalog(program_dir)
    print(f'Generated module parameter catalog: {catalog_path}', flush=True)
    print('target language: ', language_code, flush=True)
    run_lupdate(program_dir, translate_path)
    print(f'Saved to {translate_path}')
